### ISSUE TITLE
images no longer loading

### ISSUE THREAD

**Issue by eatdust** [gbour/jolla-nextinpact#10]
On current SailfishOS, pictures are no longer loading, maybe a change of API upstream.

Cheers,
Chris.

**Comment by gbour** [comment]
Thanks @eatdust, which version of JollaOS are you using ?

**Comment by eatdust** [comment]
The official release, version 2.1.0.11, named "Iijoki"!

**Comment by gbour** [comment]
This is just a change is the nextinpact html source. I updated the scraper & it is ok now

**Comment by eatdust** [comment]
Thanks, you rock! :)

**Comment by gbour** [comment]
the new release is now published on openrepos.net
