### ISSUE TITLE
Version 0.6-0 does not work on Xperia X / Mouhijoki firmware

### ISSUE THREAD

**Issue by gbour** [gbour/jolla-nextinpact#11]
It seems it fails to open the sqlite database

```
[D] Database::init:24 - cannot open sqlite database
[D] main:62 - db: Database(0xab280e30)
[W] unknown:0 - QSqlQuery::exec: database not open
```

**Comment by objectifnul** [comment]
First question: 
qtcontacts-sqlite-qt5-0.2.28-1.3.3.armv7hl
sqlite-3.13.0-1.2.1.armv7hl
qt5-plugin-sqldriver-sqlite-5.6.3+git5-1.5.2.armv7hl 

2nd question will be answered later, as I downgraded to previous nextinpact release.

**Comment by objectifnul** [comment]
Okay, I updated again to 0.6.0... and now it works! Strange. Nextinpact.db does exist now. Also, the article contents are displayed in a so small font size, I can't read them. No zoom gesture.

**Comment by objectifnul** [comment]
Additionally, screen rotation crashes the app.

**Comment by gbour** [comment]
Really strange !
Could you post again the logs of the application when it crash ?

_Also, the article contents are displayed in a so small font size, I can't read them_
Could you add a screenshot ? 
I think the fonts are small because xperia screen definition is higher than Jolla1, though it should be the same in previous releases as fonts size was not modified between 0.5 & 0.6 versions.
But I can probably improve that (note: zoom gesture does not exists on sailfishos)

_"subscribers only" indicator disappeared in the summarized view._
Where did you saw that, it was never implemented into the app

**Comment by objectifnul** [comment]
oops my mistake, sorry: the “subscribers” indicator appears on the web page.

Landscape crash log => https://send.firefox.com/download/6a24dfcb28/#eLPoCOIw4_6te27mnDtOyg 

Screenshot => https://send.firefox.com/download/1c2ea110aa/#_rjc428oC2BPm90Vyn_Jfw

**Comment by gbour** [comment]
1. Articles content is just a web frame, displaying the original article without any modification
so if the "subscribers" indicator disappears, it is because it was removed on the main website ;)

1. Regarding font size, I'll see if I can increase it

1. About the crash, I see that in log file:
```

**Comment by gbour** [comment]
Hi @objectifnul , could you try that version: https://github.com/gbour/jolla-nextinpact/releases/download/0.6.1-pre1/NextInpact-0.6-1.pre1.armv7hl.rpm ?

It should increase articles content font size.
About "subscribers only" indicateurs, it is there, look at this screen capture :)

![tag abonnes](https://user-images.githubusercontent.com/644293/50727272-e7f52200-1118-11e9-9423-2ff3b10c0453.png)

**Comment by gbour** [comment]
this version is released now
